import "~/styles/globals.css";
import { ClerkProvider, SignInButton, SignedIn, SignedOut, UserButton } from '@clerk/nextjs'
import localfont from 'next/font/local';
import { type Metadata } from "next";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};
const neueregrade = localfont({
  src: [{path: '../../public/fonts/Neue-Regrade-Variable.ttf'}],
  display: 'swap',
  weight: '100 900',
  variable: '--font-neueregrade'
});

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`  ${neueregrade.variable} no-scrollbar` }>
      <body>{children}</body>
    </html>
    </ClerkProvider>
  );
}


